# Generated by extendr: Do not edit by hand
# nolint start

#' @usage NULL
#' @useDynLib tera, .registration = TRUE
NULL

RTera <- new.env(parent = emptyenv())

RTera$new <- function() .Call(wrap__RTera__new)

RTera$new_from_glob <- function(glob) .Call(wrap__RTera__new_from_glob, glob)

RTera$full_reload <- function() .Call(wrap__RTera__full_reload, self)

RTera$add_string_templates <- function(templates) .Call(wrap__RTera__add_string_templates, self, templates)

RTera$add_file_templates <- function(templates) .Call(wrap__RTera__add_file_templates, self, templates)

RTera$render_template_to_file <- function(template_name, context_string, outfile) .Call(wrap__RTera__render_template_to_file, self, template_name, context_string, outfile)

RTera$render_template_to_string <- function(template_name, context_string) .Call(wrap__RTera__render_template_to_string, self, template_name, context_string)

RTera$render_component_to_file <- function(component_name, context_string, body, autoescape, outfile) .Call(wrap__RTera__render_component_to_file, self, component_name, context_string, body, autoescape, outfile)

RTera$render_component_to_string <- function(component_name, context_string, body, autoescape) .Call(wrap__RTera__render_component_to_string, self, component_name, context_string, body, autoescape)

RTera$render_block_to_file <- function(template_name, block_name, context_string, outfile) .Call(wrap__RTera__render_block_to_file, self, template_name, block_name, context_string, outfile)

RTera$render_block_to_string <- function(template_name, block_name, context_string) .Call(wrap__RTera__render_block_to_string, self, template_name, block_name, context_string)

RTera$render_string_to_file <- function(template_string, context_string, autoescape, outfile) .Call(wrap__RTera__render_string_to_file, self, template_string, context_string, autoescape, outfile)

RTera$render_string_to_string <- function(template_string, context_string, autoescape) .Call(wrap__RTera__render_string_to_string, self, template_string, context_string, autoescape)

RTera$autoescape_on <- function() .Call(wrap__RTera__autoescape_on, self)

RTera$autoescape_off <- function() .Call(wrap__RTera__autoescape_off, self)

RTera$set_delimiters <- function(delimiters) .Call(wrap__RTera__set_delimiters, self, delimiters)

RTera$set_globals <- function(context_string) .Call(wrap__RTera__set_globals, self, context_string)

RTera$clear_globals <- function() .Call(wrap__RTera__clear_globals, self)

RTera$get_templates <- function() .Call(wrap__RTera__get_templates, self)

RTera$get_variables <- function(template_name) .Call(wrap__RTera__get_variables, self, template_name)

RTera$get_components <- function() .Call(wrap__RTera__get_components, self)

#' @export
`$.RTera` <- function (self, name) { func <- RTera[[name]]; environment(func) <- environment(); func }

#' @export
`[[.RTera` <- `$.RTera`

# nolint end
